application: thematic-caster-124023
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: door_alarm_gae.app
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest